spring:
  rabbitmq:
      host: 192.168.1.25
      port: 5672
      addresses: 192.168.1.25:5672
      username: huayuan
      password: huayuan
      virtual-host: /
  velocity:
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8
    cache: false
  jpa:
    show-sql: true

server:
  port: 8080

##logging:
##  file: bms.log

mysql:
  enable: true
  url: "jdbc:mysql://192.168.1.25:3306/huayuan?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useAffectedRows=true&allowMultiQueries=true"
  driverClassName: "com.mysql.jdbc.Driver"
  username: "root"
  password: "root"
  initialSize: 5
  maxIdle: 10
  maxActive: 50
  validationQuery: "select 1"

redis:
  enable: true
  host: 192.168.1.25
  port: 6379
